# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{
  config,
  lib,
  pkgs,
  modulesPath,
  features,
  ...
}:
let
  defaultMountOption = [
    "compress=zstd:11"
    "ssd"
    "noatime"
    "space_cache=v2"
    "discard=async"
  ];
in
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    #"sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.loader.grub = {
    extraEntries = ''
      menuentry "Windows 11 (zh)" {
        search --fs-uuid D247-DFCF --set=root
        chainloader /EFI/Microsoft/Boot/bootmgfw.efi
      }
      menuentry "Windows 10 LTSC (jp)" {
        search --fs-uuid 209D-7E96 --set=root
        chainloader /EFI/Microsoft/Boot/bootmgfw.efi
      }
    '';
  };

  #hardware.nvidia = {
  #  modesetting.enable = true;
  #  prime = {
  #    intelBusId = "PCI:0:2:0";
  #    nvidiaBusId = "PCI:1:0:0";
  #    sync.enable = true;
  #  };
  #  powerManagement.enable = false;
  #  powerManagement.finegrained = false;
  #  open = true;
  #  nvidiaSettings = true;
  #  package = config.boot.kernelPackages.nvidiaPackages.stable;
  #};

  fileSystems."/" =
    if features.impermanence then
      {
        device = "tmpfs";
        fsType = "tmpfs";
        options = [
          "relatime"
          "mode=755"
        ];
      }
    else
      {
        device = "/dev/disk/by-uuid/3f9c46c9-efa8-4f9e-9dcf-77226f28b75b";
        fsType = "btrfs";
        options = defaultMountOption ++ [ "subvol=root" ];
      };

  fileSystems."/oldroot" = {
    device = "/dev/disk/by-uuid/3f9c46c9-efa8-4f9e-9dcf-77226f28b75b";
    fsType = "btrfs";
    options = defaultMountOption ++ [ "subvol=root" ];
    neededForBoot = true;
  };

  fileSystems."/root" = {
    device = "/dev/disk/by-uuid/3f9c46c9-efa8-4f9e-9dcf-77226f28b75b";
    fsType = "btrfs";
    options = defaultMountOption ++ [ "subvol=userroot" ];
    neededForBoot = true;
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/3f9c46c9-efa8-4f9e-9dcf-77226f28b75b";
    fsType = "btrfs";
    options = defaultMountOption ++ [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/3f9c46c9-efa8-4f9e-9dcf-77226f28b75b";
    fsType = "btrfs";
    options = defaultMountOption ++ [ "subvol=nix" ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/3f9c46c9-efa8-4f9e-9dcf-77226f28b75b";
    fsType = "btrfs";
    options = defaultMountOption ++ [ "subvol=var" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/209D-7E96";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
      "utf8"
      "noatime"
      "errors=remount-ro"
      "iocharset=ascii"
      "shortname=mixed"
    ];
  };

  swapDevices = [ ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
